name: Baguette CI2

on:
    pull_request:
        branches:
            - main
    workflow_dispatch:
    
jobs:
    hello_world_job:
        runs-on: ubuntu-latest
        steps:
            - name: Dog
              uses: actions/checkout@v2
            - name: Dog2
              run: echo ${{github.event}}
