name: Baguette CI2

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:
    
jobs:
    hello_world_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Hello world 
              run: echo ${{github.event}}
